# Generated by Django 6.0.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=255)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('client_name', models.CharField(max_length=255)),
                ('client_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('manuscript_file', models.FileField(help_text='Upload project manuscript or main file', upload_to='projects/manuscripts/%Y/%m/%d/')),
                ('project_date', models.DateField(help_text='Project start date')),
                ('deadline', models.DateField(help_text='Project deadline')),
                ('number_of_copies', models.PositiveIntegerField(default=1)),
                ('font_type', models.CharField(default='Times New Roman', help_text='Font to be used (e.g., Arial, Times New Roman, etc.)', max_length=100)),
                ('color_requirement', models.CharField(choices=[('b&w', 'Black & White'), ('color', 'Color')], default='b&w', max_length=20)),
                ('paper_type', models.CharField(default='A4', help_text='Paper size (A4, A3, Letter, etc.)', max_length=100)),
                ('binding_type', models.CharField(choices=[('spiral', 'Spiral Binding'), ('perfect', 'Perfect Binding'), ('comb', 'Comb Binding'), ('saddle_stitch', 'Saddle Stitch'), ('none', 'No Binding')], default='perfect', max_length=20)),
                ('special_instructions', models.TextField(blank=True, help_text='Any special requirements or instructions', null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Project budget if applicable', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('submitted', '📋 Submitted'), ('in_production', '🔄 In Production'), ('quality_check', '✅ Quality Check'), ('completed', '🎯 Completed'), ('ready_for_pickup', '🚚 Ready for Pickup'), ('cancelled', '❌ Cancelled')], default='submitted', max_length=20)),
                ('sent_to_production', models.BooleanField(default=False, help_text='Whether PS sent this to production')),
                ('sent_to_production_at', models.DateTimeField(blank=True, help_text='When was this sent to production', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Project Supervisor who created this', on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('view_all_projects', 'Can view all projects'), ('send_to_production', 'Can send projects to production')],
            },
        ),
        migrations.CreateModel(
            name='ProjectStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('submitted', '📋 Submitted'), ('in_production', '🔄 In Production'), ('quality_check', '✅ Quality Check'), ('completed', '🎯 Completed'), ('ready_for_pickup', '🚚 Ready for Pickup'), ('cancelled', '❌ Cancelled')], max_length=20)),
                ('new_status', models.CharField(choices=[('submitted', '📋 Submitted'), ('in_production', '🔄 In Production'), ('quality_check', '✅ Quality Check'), ('completed', '🎯 Completed'), ('ready_for_pickup', '🚚 Ready for Pickup'), ('cancelled', '❌ Cancelled')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Project Status Log',
                'verbose_name_plural': 'Project Status Logs',
            },
        ),
        migrations.CreateModel(
            name='ProjectDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_downloads', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='projects.project')),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('downloaded', '📥 Project Downloaded'), ('status_changed', '🔄 Status Changed'), ('production_complete', '✅ Production Complete')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.project')),
                ('recipient', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='production_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
