# Generated by Django 6.0.2 on 2026-05-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid so far', max_digits=10),
        ),
        migrations.AddField(
            model_name='project',
            name='balance_remaining',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Balance remaining to be paid', max_digits=10),
        ),
        migrations.AddField(
            model_name='project',
            name='project_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total project amount', max_digits=10),
        ),
    ]
