# Generated by Django 6.0.2 on 2026-05-04 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_leads', '0005_joborder'),
        ('projects', '0002_project_amount_paid_project_balance_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source_job_order',
            field=models.ForeignKey(blank=True, help_text='Original sales job order source', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='crm_leads.joborder'),
        ),
        migrations.AlterField(
            model_name='project',
            name='manuscript_file',
            field=models.FileField(blank=True, help_text='Upload project manuscript or main file', null=True, upload_to='projects/manuscripts/%Y/%m/%d/'),
        ),
    ]
