# Generated by Django 6.0.2 on 2026-05-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_source_job_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='project',
            name='balance_remaining',
        ),
        migrations.RemoveField(
            model_name='project',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_amount',
        ),
        migrations.AddField(
            model_name='project',
            name='agreed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Agreed amount for the project', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Balance due for the project', max_digits=10),
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated budget for the project', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='isbn_required',
            field=models.BooleanField(default=False, help_text='Whether an ISBN is required for this project'),
        ),
        migrations.AddField(
            model_name='project',
            name='paper_size',
            field=models.CharField(blank=True, help_text='Paper size (e.g., A4, A3, Letter)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='paper_weight',
            field=models.CharField(blank=True, help_text='Paper weight (e.g., 80gsm, 100gsm)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='part_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Part payment amount paid so far', max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='paper_type',
            field=models.CharField(default='A4', help_text='Paper type or format (A4, A3, Letter, etc.)', max_length=100),
        ),
    ]
