# Generated by Django 6.0.2 on 2026-05-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_location',
            field=models.CharField(blank=True, help_text='Client address or location', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='delivery_location',
            field=models.CharField(blank=True, help_text='Delivery address or location', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='line_spacing',
            field=models.CharField(blank=True, help_text='Line spacing for the manuscript (e.g., single, 1.5, double)', max_length=20, null=True),
        ),
    ]
