# Generated by Django 6.0.2 on 2026-05-04 10:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_leads', '0004_lead_awaiting_at_alter_lead_status_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(help_text='Auto-generated order number', max_length=20, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Order date')),
                ('customer_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('product_service', models.CharField(choices=[('book_printing', 'Book Printing'), ('complete_publishing', 'Complete Publishing'), ('isbn_procurement', 'ISBN Procurement'), ('poster_printing', 'Poster Printing'), ('flyer_printing', 'Flyer Printing'), ('business_card', 'Business Card'), ('shirt_printing', 'Shirt Printing'), ('roll_up_banner', 'Roll Up Banner'), ('program_booklet', 'Program Booklet'), ('other_service', 'Other Service')], default='book_printing', max_length=20)),
                ('title_description', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('size_dimension', models.CharField(choices=[('a4', 'A4'), ('a3', 'A3'), ('letter', 'Letter'), ('custom', 'Custom')], default='a4', max_length=20)),
                ('color_mode', models.CharField(choices=[('b&w', 'Black & White'), ('color', 'Color'), ('cmyk', 'CMYK')], default='b&w', max_length=20)),
                ('paper_type', models.CharField(choices=[('standard', 'Standard'), ('glossy', 'Glossy'), ('matte', 'Matte'), ('cardstock', 'Cardstock')], default='standard', max_length=20)),
                ('paper_weight', models.CharField(blank=True, help_text='e.g., 80gsm, 100gsm', max_length=20, null=True)),
                ('binding', models.CharField(choices=[('spiral', 'Spiral'), ('perfect', 'Perfect'), ('comb', 'Comb'), ('saddle_stitch', 'Saddle Stitch'), ('none', 'None')], default='none', max_length=20)),
                ('lamination', models.CharField(choices=[('none', 'None'), ('glossy', 'Glossy'), ('matte', 'Matte')], default='none', max_length=20)),
                ('total_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('design_needed', models.CharField(choices=[('cover_inner', 'Yes - Cover & Inner'), ('cover_only', 'Yes - Cover Only'), ('no', 'No - I Have Design')], default='no', max_length=20)),
                ('design_concepts', models.CharField(blank=True, choices=[('1', '1 Concept'), ('2', '2 Concepts'), ('3', '3 Concepts')], max_length=20, null=True)),
                ('design_style', models.CharField(blank=True, choices=[('modern', 'Modern'), ('classic', 'Classic'), ('minimal', 'Minimal'), ('custom', 'Custom')], max_length=20, null=True)),
                ('font_type', models.CharField(blank=True, max_length=100, null=True)),
                ('font_size', models.CharField(blank=True, max_length=20, null=True)),
                ('line_spacing', models.CharField(blank=True, choices=[('single', 'Single'), ('1.5', '1.5'), ('double', 'Double')], max_length=20, null=True)),
                ('isbn_required', models.BooleanField(default=False)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('delivery_mode', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery'), ('shipping', 'Shipping')], default='pickup', max_length=20)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('urgency_level', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('rush', 'Rush')], default='normal', max_length=20)),
                ('source_of_deal', models.CharField(choices=[('walk_in', 'Walk In'), ('phone', 'Phone'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('website', 'Website'), ('referral', 'Referral')], default='walk_in', max_length=20)),
                ('estimated_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('agreed_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('part_payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='job_orders/invoices/%Y/%m/%d/')),
                ('manuscript_file', models.FileField(blank=True, null=True, upload_to='job_orders/manuscripts/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent_to_project', 'Sent to Project'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_job_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
