"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

import os
from pathlib import Path
from urllib.parse import urlparse

# --------------------------------------------------
# Base directory
# --------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent


# --------------------------------------------------
# Security
# --------------------------------------------------
# Use DJANGO_SECRET_KEY from Render, fallback to insecure key for local dev
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-=klap(oqw72fp2yd!f9s&u$4p1$ixx^mbiyi=qboonoq12o-n-'
)

# Check DJANGO_DEBUG first (Render), then DEBUG (local)
DEBUG = os.getenv('DJANGO_DEBUG', os.getenv('DEBUG', 'True')).lower() == 'true'

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    'thecworkflow.com',
    'www.thecworkflow.com',
    '.onrender.com',
    'thecworkflow-crm.onrender.com'
]



# --------------------------------------------------
# Applications
# --------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Local apps
    'accounts',
    # original crm_leads app (contains Lead, LeadActivity, etc.)
    'crm_leads',
    'dashboards',
    'projects',  # 👈 NEW: Project Management & Production Room
]


# --------------------------------------------------
# Middleware
# --------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# --------------------------------------------------
# URLs / Templates
# --------------------------------------------------
ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        # keep this – required for custom login template
        'DIRS': [BASE_DIR / 'templates'],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# --------------------------------------------------
# Database
# --------------------------------------------------
import os
from urllib.parse import urlparse
DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    url = urlparse(DATABASE_URL)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": url.path[1:],
            "USER": url.username,
            "PASSWORD": url.password,
            "HOST": url.hostname,
            "PORT": url.port,
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }



# --------------------------------------------------
# Password validation
# --------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# --------------------------------------------------
# Internationalization
# --------------------------------------------------
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True
USE_TZ = True


# --------------------------------------------------
# Static files
# --------------------------------------------------
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]


# --------------------------------------------------
# Media files (User uploads)
# --------------------------------------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'



# --------------------------------------------------
# AUTHENTICATION (CRITICAL FIX)
# --------------------------------------------------

# Use your custom login page (NOT admin)
LOGIN_URL = '/accounts/login/'

# After successful login, send users to the router that selects the right dashboard by role
LOGIN_REDIRECT_URL = '/'

# After logout, go back to login page
LOGOUT_REDIRECT_URL = '/accounts/login/'


# --------------------------------------------------
# SESSION & CSRF SECURITY (PRODUCTION FIX)
# --------------------------------------------------

# Store sessions in database (persistent across server restarts)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Session timeout (in seconds) - 2 weeks
SESSION_COOKIE_AGE = 1209600

# Ensure session cookies are secure in production
SESSION_COOKIE_SECURE = not DEBUG  # Only HTTPS in production
SESSION_COOKIE_HTTPONLY = True      # Prevent JavaScript access
SESSION_COOKIE_SAMESITE = 'Lax'     # CSRF protection

# CSRF token protection
CSRF_COOKIE_SECURE = not DEBUG      # Only HTTPS in production
CSRF_COOKIE_HTTPONLY = False        # JavaScript needs to read CSRF token
CSRF_COOKIE_SAMESITE = 'Lax'        # CSRF protection

# Trusted origins for CSRF (add your production domain)
CSRF_TRUSTED_ORIGINS = [
    'https://thecworkflow.com',
    'https://www.thecworkflow.com',
    'https://*.onrender.com',
]


# --------------------------------------------------
# Default primary key field type
# --------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
